#Environment Variables

In [1]:
import os

os.environ["HF_TOKEN"]="Your HF-TOKEN"
os.environ["COMET_API_KEY"]="Your COMET-API-KEY"

#Imports

In [3]:
import comet_ml
import torch
from unsloth import FastLanguageModel, is_bfloat16_supported
from trl import DPOTrainer,DPOConfig
from transformers import TextStreamer
from datasets import load_dataset

#Login to Comet ML

In [4]:
comet_ml.login()

In [5]:
exp=comet_ml.start(project_name="llm_twin_fine_tuning_dpo_model")

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, torch.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/spiralmonster/llm-twin-fine-tuning-dpo-model/6ce4e1b55bfb40b3b910c625b4623726

#Load Model

In [7]:
HF_USERNAME="spiralMon"
model_name="Twin-LLM-Fine-Tuned-Instruct-Model-Llama-3.1-8B-bnb-4bit"
model_id=HF_USERNAME+"/"+model_name

In [8]:
max_seq_length=2048

In [9]:
model,tokenizer=FastLanguageModel.from_pretrained(
    model_name=model_id,
    max_seq_length=max_seq_length,
    load_in_4bit=True,
    device_map="cuda"
)

==((====))==  Unsloth 2026.8.14: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load spiralMon/Twin-LLM-Fine-Tuned-Instruct-Model-Llama-3.1-8B-bnb-4bit as a legacy tokenizer.

# Create PEFT Model

In [10]:
lora_rank=32
lora_alpha=32
lora_dropout=0
target_modules=[
    "q_proj",
    "k_proj",
    "v_proj",
    "up_proj",
    "down_proj",
    "o_proj",
    "gate_proj"
]

In [12]:
model=FastLanguageModel.get_peft_model(
    model,
    r=lora_rank,
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    target_modules=target_modules
)

Unsloth 2026.8.14 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

#Load Dataset

In [13]:
dataset_name="llm_twin_preference_dataset"
dataset_id=HF_USERNAME+"/"+dataset_name

In [14]:
dataset=load_dataset(dataset_id)

README.md:   0%|          | 0.00/369 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  823kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/2163 [00:00<?, ? examples/s]

In [15]:
dataset=dataset["train"]

In [16]:
dataset

Dataset({
    features: ['instructions', 'chosen_answers', 'rejected_answers'],
    num_rows: 2163
})

#Format Dataset

In [17]:
alpaca_template="""
Below is an instruction that describes a task.Write a response that appropriately completes the request.

### Instruction:
{}

### Response:
"""

In [18]:
EOS_TOKEN=tokenizer.eos_token

In [19]:
def format_samples(example):
  prompt=alpaca_template.format(
      example["instructions"]
  )
  chosen=example["chosen_answers"]+EOS_TOKEN
  rejected=example["rejected_answers"]+EOS_TOKEN

  result={
      "prompt":prompt,
      "chosen":chosen,
      "rejected":rejected
  }

  return result

In [20]:
dataset=dataset.map(format_samples)

Map:   0%|          | 0/2163 [00:00<?, ? examples/s]

In [22]:
dataset=dataset.remove_columns([
    "instructions",
    "chosen_answers",
    "rejected_answers"
])

In [24]:
dataset=dataset.train_test_split(
    test_size=0.05
)

In [25]:
dataset

DatasetDict({
    train: Dataset({
        features: ['prompt', 'chosen', 'rejected'],
        num_rows: 2054
    })
    test: Dataset({
        features: ['prompt', 'chosen', 'rejected'],
        num_rows: 109
    })
})

#Model Fine-Tuning

In [27]:
training_arguments=DPOConfig(
    learning_rate=2e-6,
    lr_scheduler_type="linear",
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    num_train_epochs=3,
    fp16=not is_bfloat16_supported(),
    bf16=is_bfloat16_supported(),
    optim="adamw_8bit",
    weight_decay=0.01,
    warmup_steps=10,
    output_dir="output",
    eval_strategy="steps",
    eval_steps=0.2,
    logging_steps=1,
    report_to="comet_ml",
    seed=0
)

In [28]:
trainer=DPOTrainer(
    model=model,
    ref_model=None,
    tokenizer=tokenizer,
    beta=0.5,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    max_length=max_seq_length//2,
    max_prompt_length=max_seq_length//2,
    args=training_arguments
)

Extracting prompt in train dataset (num_proc=2):   0%|          | 0/2054 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=2):   0%|          | 0/2054 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=2):   0%|          | 0/2054 [00:00<?, ? examples/s]

Extracting prompt in eval dataset (num_proc=2):   0%|          | 0/109 [00:00<?, ? examples/s]

Applying chat template to eval dataset (num_proc=2):   0%|          | 0/109 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=2):   0%|          | 0/109 [00:00<?, ? examples/s]

In [29]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 2,054 | Num Epochs = 3 | Total steps = 387
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 83,886,080 of 8,114,147,328 (1.03% trained)
COMET INFO: An experiment with the same configuration options is already running and will be reused.
COMET WARNING: String value length exceeds 1000 characters and will be truncated. Provided value: 'LoraConfig(task_type=<TaskType.CAUSAL_LM: 'CAUSAL_LM'>, peft_type=<PeftType.LORA: 'LORA'>, auto_mapping={'base_model_class': 'LlamaForCausalLM', 'parent_library': 'transformers.models.llama.modeling_llama', 'unsloth_fixed': True}, peft_version='0.19.1', base_model_name_or_path='spiralMon/Twin-LLM-Fine-Tuned-Instruct-Model-Llama-3.1-8B-bnb-4bit', revision=None, inference_mode=False, r=32, target_modules={'q_proj', 'k_proj', 'down_proj', 'gate_proj', 'up_proj', 'o_proj', 'v_proj'}, exclude_modules=None, lora_alpha=32, lora_dropout=0, fan_in_fan_out=False, bias='none', use_rslora=False, modules_to_save=None, init_lora_weights=True, layers_to_transform=None, layers_pattern=None, rank_pattern={}, alpha_pattern={}, megatron_config=None, megatron_core='megatron.core', trainable_token_indices=None, loftq_config={}, eva_config=None, corda_config=None, lora_ga_config=None, use_dora=False, alora_invocation_tokens=None, use_qalora=False, qalora_group_size=16, layer_replication=None, runtime_config=LoraRuntimeConfig(ephemeral_gpu_offload=False), lora_bias=False, target_parameters=None, use_bdlora=None, arrow_config=None, ensure_weight_tying=False)'
`use_return_dict` is deprecated! Use `return_dict` instead!

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Restored added_tokens_decoder metadata in output/checkpoint-387/tokenizer_config.json.

TrainOutput(global_step=387, training_loss=0.10512414960869292, metrics={'train_runtime': 8499.0591, 'train_samples_per_second': 0.725, 'train_steps_per_second': 0.046, 'total_flos': 0.0, 'train_loss': 0.10512414960869292, 'epoch': 3.0})

In [30]:
exp.end()

COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : northern_granite_5475
COMET INFO:     url                   : https://www.comet.com/spiralmonster/llm-twin-fine-tuning-dpo-model/6ce4e1b55bfb40b3b910c625b4623726
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     eval/logits/chosen [5]         : (-1.7036583423614502, -1.6898434162139893)
COMET INFO:     eval/logits/rejected [5]       : (-1.6213696002960205, -1.5917046070098877)
COMET INFO:     eval/logps/chosen [5]          : (-224.20913696289062, -215.12815856933594)
COMET INFO:     eval/logps/rejected [5]        : (-112.5619125366211, -109.87642669677734)
COMET INFO:     eval/loss [5]                  : (0.019348029047250748, 0.14624658226966858)
COMET INFO:     eval/rewards/accuracies [5]    : (0.9909090995788574, 1.0)
COMET INFO:     eval/rewards/chosen [5]        : (2.6466240882873535, 7.187112808227539)
COMET INFO:     eval/rewards/margins [5]       : (2.4165000915527344, 8.080341339111328)
COMET INFO:     eval/rewards/rejected [5]      : (-0.8932287096977234, 0.4495217204093933)
COMET INFO:     eval/runtime [5]               : (74.4545, 85.1759)
COMET INFO:     eval/samples_per_second [5]    : (1.28, 1.464)
COMET INFO:     eval/steps_per_second [5]      : (0.646, 0.739)
COMET INFO:     train/epoch [393]              : (0.007789678675754625, 3.0)
COMET INFO:     train/grad_norm [387]          : (0.034111056476831436, 11.925533294677734)
COMET INFO:     train/learning_rate [387]      : (0.0, 2e-06)
COMET INFO:     train/logits/chosen [387]      : (-1.9154844284057617, -1.165916919708252)
COMET INFO:     train/logits/rejected [387]    : (-1.9114383459091187, -1.3635177612304688)
COMET INFO:     train/logps/chosen [387]       : (-301.43316650390625, -130.28138732910156)
COMET INFO:     train/logps/rejected [387]     : (-128.55751037597656, -81.64142608642578)
COMET INFO:     train/loss [387]               : (0.0005285721272230148, 0.6964035034179688)
COMET INFO:     train/rewards/accuracies [387] : (0.0, 1.0)
COMET INFO:     train/rewards/chosen [387]     : (0.0, 8.146529197692871)
COMET INFO:     train/rewards/margins [387]    : (-0.006335735321044922, 10.392602920532227)
COMET INFO:     train/rewards/rejected [387]   : (-3.2772727012634277, 1.4492536783218384)
COMET INFO:     train/total_flos               : 0.0
COMET INFO:     train/train_loss               : 0.10512414960869292
COMET INFO:     train/train_runtime            : 8499.0591
COMET INFO:     train/train_samples_per_second : 0.725
COMET INFO:     train/train_steps_per_second   : 0.046
COMET INFO:   Others:
COMET INFO:     hasNestedParams : True
COMET INFO:     notebook_url    : https://colab.research.google.com/notebook#fileId=1pmaBgX7AEOvyFtY8tXyM0aDsPS_pIu5e
COMET INFO:   Parameters:
COMET INFO:     args|accelerator_config|dispatch_batches                    : None
COMET INFO:     args|accelerator_config|even_batches                        : True
COMET INFO:     args|accelerator_config|gradient_accumulation_kwargs        : None
COMET INFO:     args|accelerator_config|non_blocking                        : False
COMET INFO:     args|accelerator_config|split_batches                       : False
COMET INFO:     args|accelerator_config|use_seedable_sampler                : True
COMET INFO:     args|adam_beta1                                             : 0.9
COMET INFO:     args|adam_beta2                                             : 0.999
COMET INFO:     args|adam_epsilon                                           : 1e-08
COMET INFO:     args|auto_find_batch_size                                   : False
COMET INFO:     args|average_tokens_across_devices                          : True
COMET INFO:     args|base_model_attribute_name                              : model
COMET INFO:     args|batch_eval_metrics                                     : False
COMET INFO:     args|beta                                                   : 0.5
COMET INFO:     args|bf16                                                   : False
COMET INFO:     args|bf16_full_eval                                         : False
COMET INFO:     args|data_seed                                              : 3407
COMET INFO:     args|dataloader_drop_last                                   : False
COMET INFO:     args|dataloader_num_workers                                 : 0
COMET INFO:     args|dataloader_persistent_workers                          : False
COMET INFO:     args|dataloader_pin_memory                                  : True
COMET INFO:     args|dataloader_prefetch_factor                             : None
COMET INFO:     args|dataset_num_proc                                       : 2
COMET INFO:     args|ddp_backend                                            : None
COMET INFO:     args|ddp_broadcast_buffers                                  : None
COMET INFO:     args|ddp_bucket_cap_mb                                      : None
COMET INFO:     args|ddp_find_unused_parameters                             : None
COMET INFO:     args|ddp_timeout                                            : 1800
COMET INFO:     args|debug                                                  : []
COMET INFO:     args|deepspeed                                              : None
COMET INFO:     args|disable_dropout                                        : True
COMET INFO:     args|disable_tqdm                                           : False
COMET INFO:     args|discopop_tau                                           : 0.05
COMET INFO:     args|do_eval                                                : True
COMET INFO:     args|do_predict                                             : False
COMET INFO:     args|do_train                                               : False
COMET INFO:     args|enable_jit_checkpoint                                  : False
COMET INFO:     args|eval_accumulation_steps                                : 2
COMET INFO:     args|eval_delay                                             : 0
COMET INFO:     args|eval_do_concat_batches                                 : True
COMET INFO:     args|eval_on_start                                          : False
COMET INFO:     args|eval_steps                                             : 0.2
COMET INFO:     args|eval_strategy                                          : steps
COMET INFO:     args|eval_use_gather_object                                 : False
COMET INFO:     args|f_alpha_divergence_coef                                : 1.0
COMET INFO:     args|f_divergence_type                                      : reverse_kl
COMET INFO:     args|force_use_ref_model                                    : False
COMET INFO:     args|fp16                                                   : True
COMET INFO:     args|fp16_full_eval                                         : True
COMET INFO:     args|fsdp                                                   : []
COMET INFO:     args|fsdp_config|min_num_params                             : 0
COMET INFO:     args|fsdp_config|xla                                        : False
COMET INFO:     args|fsdp_config|xla_fsdp_grad_ckpt                         : False
COMET INFO:     args|fsdp_config|xla_fsdp_v2                                : False
COMET INFO:     args|full_determinism                                       : False
COMET INFO:     args|generate_during_eval                                   : False
COMET INFO:     args|gradient_accumulation_steps                            : 8
COMET INFO:     args|gradient_checkpointing                                 : True
COMET INFO:     args|gradient_checkpointing_kwargs                          : None
COMET INFO:     args|greater_is_better                                      : None
COMET INFO:     args|hub_always_push                                        : False
COMET INFO:     args|hub_model_id                                           : None
COMET INFO:     args|hub_private_repo                                       : None
COMET INFO:     args|hub_revision                                           : None
COMET INFO:     args|hub_strategy                                           : every_save
COMET INFO:     args|hub_token                                              : <HUB_TOKEN>
COMET INFO:     args|ignore_data_skip                                       : False
COMET INFO:     args|include_for_metrics                                    : []
COMET INFO:     args|include_num_input_tokens_seen                          : no
COMET INFO:     args|label_names                                            : None
COMET INFO:     args|label_pad_token_id                                     : -100
COMET INFO:     args|label_smoothing                                        : 0.0
COMET INFO:     args|label_smoothing_factor                                 : 0.0
COMET INFO:     args|ld_alpha                                               : None
COMET INFO:     args|learning_rate                                          : 2e-06
COMET INFO:     args|length_column_name                                     : length
COMET INFO:     args|liger_kernel_config                                    : None
COMET INFO:     args|load_best_model_at_end                                 : False
COMET INFO:     args|local_rank                                             : -1
COMET INFO:     args|log_level                                              : passive
COMET INFO:     args|log_level_replica                                      : warning
COMET INFO:     args|log_on_each_node                                       : True
COMET INFO:     args|logging_dir                                            : None
COMET INFO:     args|logging_first_step                                     : False
COMET INFO:     args|logging_nan_inf_filter                                 : False
COMET INFO:     args|logging_steps                                          : 1
COMET INFO:     args|logging_strategy                                       : steps
COMET INFO:     args|loss_type                                              : sigmoid
COMET INFO:     args|loss_weights                                           : None
COMET INFO:     args|lr_scheduler_kwargs                                    : None
COMET INFO:     args|lr_scheduler_type                                      : linear
COMET INFO:     args|max_completion_length                                  : None
COMET INFO:     args|max_grad_norm                                          : 1.0
COMET INFO:     args|max_length                                             : 1024
COMET INFO:     args|max_prompt_length                                      : 1024
COMET INFO:     args|max_seq_length                                         : 2048
COMET INFO:     args|max_steps                                              : -1
COMET INFO:     args|metric_for_best_model                                  : None
COMET INFO:     args|model_adapter_name                                     : None
COMET INFO:     args|model_init_kwargs                                      : None
COMET INFO:     args|neftune_noise_alpha                                    : None
COMET INFO:     args|num_train_epochs                                       : 3
COMET INFO:     args|optim                                                  : adamw_8bit
COMET INFO:     args|optim_args                                             : None
COMET INFO:     args|optim_target_modules                                   : None
COMET INFO:     args|output_dir                                             : output
COMET INFO:     args|pad_token                                              : <PAD_TOKEN>
COMET INFO:     args|padding_free                                           : None
COMET INFO:     args|padding_value                                          : None
COMET INFO:     args|parallelism_config                                     : None
COMET INFO:     args|per_device_eval_batch_size                             : 2
COMET INFO:     args|per_device_train_batch_size                            : 2
COMET INFO:     args|precompute_ref_batch_size                              : None
COMET INFO:     args|precompute_ref_log_probs                               : False
COMET INFO:     args|prediction_loss_only                                   : False
COMET INFO:     args|project                                                : huggingface
COMET INFO:     args|push_to_hub                                            : False
COMET INFO:     args|push_to_hub_token                                      : None
COMET INFO:     args|ref_adapter_name                                       : None
COMET INFO:     args|ref_model_init_kwargs                                  : None
COMET INFO:     args|ref_model_mixup_alpha                                  : 0.6
COMET INFO:     args|ref_model_sync_steps                                   : 512
COMET INFO:     args|reference_free                                         : False
COMET INFO:     args|remove_unused_columns                                  : True
COMET INFO:     args|report_to                                              : ['comet_ml']
COMET INFO:     args|restore_callback_states_from_checkpoint                : False
COMET INFO:     args|resume_from_checkpoint                                 : None
COMET INFO:     args|rpo_alpha                                              : None
COMET INFO:     args|run_name                                               : None
COMET INFO:     args|save_on_each_node                                      : False
COMET INFO:     args|save_only_model                                        : False
COMET INFO:     args|save_steps                                             : 500
COMET INFO:     args|save_strategy                                          : steps
COMET INFO:     args|save_total_limit                                       : None
COMET INFO:     args|seed                                                   : 0
COMET INFO:     args|skip_memory_metrics                                    : True
COMET INFO:     args|sync_ref_model                                         : False
COMET INFO:     args|tf32                                                   : None
COMET INFO:     args|tools                                                  : None
COMET INFO:     args|torch_compile                                          : False
COMET INFO:     args|torch_compile_backend                                  : None
COMET INFO:     args|torch_compile_mode                                     : None
COMET INFO:     args|torch_empty_cache_steps                                : 250
COMET INFO:     args|trackio_space_id                                       : trackio
COMET INFO:     args|train_sampling_strategy                                : random
COMET INFO:     args|truncation_mode                                        : keep_end
COMET INFO:     args|unsloth_grpo_mini_batch                                : None
COMET INFO:     args|unsloth_logit_chunk_multiplier                         : None
COMET INFO:     args|unsloth_num_chunks                                     : -1
COMET INFO:     args|use_cache                                              : False
COMET INFO:     args|use_cpu                                                : False
COMET INFO:     args|use_liger_kernel                                       : False
COMET INFO:     args|use_liger_loss                                         : False
COMET INFO:     args|use_logits_to_keep                                     : False
COMET INFO:     args|use_weighting                                          : False
COMET INFO:     args|vllm_sampling_params                                   : None
COMET INFO:     args|warmup_ratio                                           : None
COMET INFO:     args|warmup_steps                                           : 10
COMET INFO:     args|weight_decay                                           : 0.01
COMET INFO:     config|_name_or_path                                        : spiralMon/Twin-LLM-Fine-Tuned-Instruct-Model-Llama-3.1-8B-bnb-4bit
COMET INFO:     config|architectures                                        : ['LlamaForCausalLM']
COMET INFO:     config|attention_bias                                       : False
COMET INFO:     config|attention_dropout                                    : 0.0
COMET INFO:     config|bos_token_id                                         : 128000
COMET INFO:     config|chunk_size_feed_forward                              : 0
COMET INFO:     config|dtype                                                : float16
COMET INFO:     config|eos_token_id                                         : 128001
COMET INFO:     config|head_dim                                             : 128
COMET INFO:     config|hidden_act                                           : silu
COMET INFO:     config|hidden_size                                          : 4096
COMET INFO:     config|id2label|0                                           : LABEL_0
COMET INFO:     config|id2label|1                                           : LABEL_1
COMET INFO:     config|initializer_range                                    : 0.02
COMET INFO:     config|intermediate_size                                    : 14336
COMET INFO:     config|is_encoder_decoder                                   : False
COMET INFO:     config|label2id|LABEL_0                                     : 0
COMET INFO:     config|label2id|LABEL_1                                     : 1
COMET INFO:     config|max_position_embeddings                              : 131072
COMET INFO:     config|mlp_bias                                             : False
COMET INFO:     config|model_type                                           : llama
COMET INFO:     config|num_attention_heads                                  : 32
COMET INFO:     config|num_hidden_layers                                    : 32
COMET INFO:     config|num_key_value_heads                                  : 8
COMET INFO:     config|output_attentions                                    : False
COMET INFO:     config|output_hidden_states                                 : False
COMET INFO:     config|pad_token_id                                         : 128004
COMET INFO:     config|pretraining_tp                                       : 1
COMET INFO:     config|problem_type                                         : None
COMET INFO:     config|quantization_config|bnb_4bit_compute_dtype           : float16
COMET INFO:     config|quantization_config|bnb_4bit_quant_type              : nf4
COMET INFO:     config|quantization_config|bnb_4bit_use_double_quant        : True
COMET INFO:     config|quantization_config|llm_int8_enable_fp32_cpu_offload : False
COMET INFO:     config|quantization_config|llm_int8_has_fp16_weight         : False
COMET INFO:     config|quantization_config|llm_int8_skip_modules            : None
COMET INFO:     config|quantization_config|llm_int8_threshold               : 6.0
COMET INFO:     config|quantization_config|load_in_4bit                     : True
COMET INFO:     config|quantization_config|load_in_8bit                     : False
COMET INFO:     config|quantization_config|quant_method                     : bitsandbytes
COMET INFO:     config|return_dict                                          : True
COMET INFO:     config|rms_norm_eps                                         : 1e-05
COMET INFO:     config|rope_parameters|factor                               : 8.0
COMET INFO:     config|rope_parameters|high_freq_factor                     : 4.0

#Testing the Fine-Tuned Model

In [31]:
test_model=FastLanguageModel.for_inference(model)

In [36]:
input_prompt=alpaca_template.format(
    "Write an article about how to find a good partner?",
    ""
)

In [37]:
model_input=tokenizer([input_prompt],return_tensors="pt").to("cuda")

In [38]:
text_streamer=TextStreamer(tokenizer)

In [39]:
output=model.generate(
    **model_input,
    streamer=text_streamer,
    max_new_tokens=256,
    use_cache=True
)

<|begin_of_text|>
Below is an instruction that describes a task.Write a response that appropriately completes the request.

### Instruction:
Write an article about how to find a good partner?

### Response:

Both `max_new_tokens` (=256) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

The search for a good partner is a complex and often frustrating process. However, the key to finding a good partner is not in the search itself, but in the search for the search. The search for the search is a process of self-reflection and self-discovery, where one must first understand their own values, needs, and priorities before they can effectively evaluate potential partners. This requires a deep understanding of one's own desires and what truly matters to them, and a willingness to be honest and transparent about these things. Only then can one truly find a partner who aligns with their values and goals, and who can provide the support and stability they need in life.
<|end_of_text|>

#Publishing Model to Hugging Face Hub

In [40]:
model_name="Twin-LLM-Fine-Tuned-DPO-Model-Llama-3.1-8B"
model_id=HF_USERNAME+"/"+model_name

In [41]:
model.push_to_hub_merged(
    model_id,
    tokenizer,
    save_method="merged_16bit"
)

Unsloth: Restored added_tokens_decoder metadata in spiralMon/Twin-LLM-Fine-Tuned-DPO-Model-Llama-3.1-8B/tokenizer_config.json.

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:205: UserWarning: The `local_dir_use_symlinks` argument is deprecated and ignored in `snapshot_download`. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Checking cache directory for required files...

Unsloth: Copying 4 files from cache to `spiralMon/Twin-LLM-Fine-Tuned-DPO-Model-Llama-3.1-8B`:   0%|          | 0/4 [00:00<?, ?it/s]

Unsloth: Copying 4 files from cache to `spiralMon/Twin-LLM-Fine-Tuned-DPO-Model-Llama-3.1-8B`:  25%|██▌       | 1/4 [01:38<04:54, 98.23s/it]

Unsloth: Copying 4 files from cache to `spiralMon/Twin-LLM-Fine-Tuned-DPO-Model-Llama-3.1-8B`:  50%|█████     | 2/4 [03:24<03:26, 103.05s/it]

Unsloth: Copying 4 files from cache to `spiralMon/Twin-LLM-Fine-Tuned-DPO-Model-Llama-3.1-8B`:  75%|███████▌  | 3/4 [05:12<01:45, 105.08s/it]

Unsloth: Copying 4 files from cache to `spiralMon/Twin-LLM-Fine-Tuned-DPO-Model-Llama-3.1-8B`: 100%|██████████| 4/4 [05:41<00:00, 85.45s/it]

Successfully copied all 4 files from cache to `spiralMon/Twin-LLM-Fine-Tuned-DPO-Model-Llama-3.1-8B`
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files: 100%|██████████| 4/4 [00:00<00:00, 33222.21it/s]


Unsloth: Merging weights into 16bit:   0%|          | 0/4 [00:00<?, ?it/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Unsloth: Merging weights into 16bit:  25%|██▌       | 1/4 [03:01<09:04, 181.64s/it]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Unsloth: Merging weights into 16bit:  50%|█████     | 2/4 [06:28<06:32, 196.34s/it]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Unsloth: Merging weights into 16bit:  75%|███████▌  | 3/4 [09:54<03:20, 200.86s/it]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Unsloth: Merging weights into 16bit: 100%|██████████| 4/4 [10:20<00:00, 155.10s/it]

Unsloth: Merge process complete. Saved to `/content/spiralMon/Twin-LLM-Fine-Tuned-DPO-Model-Llama-3.1-8B`